server:
  port: 8080
spring:
  application:
    name: user-ms
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  jackson:
    time-zone: IST
  config:
    import:
    - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: qa
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
my-properties:
  value: 4321
  