server:
  port: 8080
spring:
  application:
    name: user-ms
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  jackson:
    time-zone: IST
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"